### ISSUE TITLE
Descriptors  don't include the license file

### ISSUE THREAD

**Issue by puntogil** [shrinkwrap/descriptors#104]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by aslakknutsen** [comment]
Thank you for pointing that out!

FYI, the active release branch is 2.0.0-X
