### ISSUE TITLE
Final version of 2.0.0

### ISSUE THREAD

**Issue by heiko-braun** [shrinkwrap/descriptors#110]
Can we get a final version of 2.0.0 to be included in Wildfly Swarm? It seems 2.0.0.Alpha9 had quite some bake time, do you think it can be released or does anything hold it back?

The related issue: https://issues.jboss.org/browse/SWARM-1319

**Comment by lordofthejars** [comment]
+1 to me, no blockers, I'll talk with Matous and release it if no blockers

**Comment by heiko-braun** [comment]
great, thanks @lordofthejars

**Comment by MatousJobanek** [comment]
+1 from my side and no blockers

**Comment by lordofthejars** [comment]
cool I am going to do it then

**Comment by lordofthejars** [comment]
@heiko-braun released to jboss nexus. Now waiting until synced.

**Comment by heiko-braun** [comment]
Thanks for the quick turn around @lordofthejars !
